version: '3'
services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8080:80
    volumes:
      - images:/var/www/html/images
      # After initial setup, download LocalSettings.php to `/var/www/html/LocalSettings.php`

volumes:
  images:

