version: "3"

services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    ports:
      - "5244:5244"
    restart: unless-stopped
    volumes:
      - /opt/alist/data:/opt/alist/data
      - /opt/alist/storage:/opt/alist/storage
