version: "3"

services:
  alist:
    container_name: alist
    restart: unless-stopped
    image: xhofe/alist:latest
    ports:
      - "5244:5244"
    volumes:
      - alist:/opt/alist/data
volumes:
  alist:
