version: '3.3'
services:
    frpc:
        restart: always
        network_mode: host
        volumes:
            - '/home/jyf/.config/frp/frpc.ini:/etc/frp/frpc.ini'
        container_name: frpc
        image: snowdreamtech/frpc
