version: '3'

services:

  miniflux:
    container_name: miniflux
    restart: unless-stopped
    image: miniflux/miniflux:latest
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=123456
      - BASE_URL=https://miniflux.app/
      - CREATE_ADMIN=1
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
      - RUN_MIGRATIONS=1

  db:
    container_name: miniflux-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux_db:/var/lib/postgresql/data

volumes:
  miniflux_db:
