version: "3"
services:
  navidrome:
    container_name: navidrome
    restart: unless-stopped
    image: deluan/navidrome:latest
    ports:
      - 4533:4533
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - navidrome_data:/data
      - navidrome_music:/music
volumes:
  navidrome_data:
  navidrome_music:
