version: '3'

services:
  app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - nextcloud_netbridge
    links:
      - db
    volumes:
      - nextcloud_app:/var/www/html
    environment:
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  db:
    image: mariadb:10.5
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks:
      - nextcloud_netbridge
    volumes:
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

volumes:
  nextcloud_db:
  nextcloud_app:


networks:
  nextcloud_netbridge:
    driver: bridge
