version: "3.0"
services:
  web:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    volumes:
        - /etc/nginx/nginx.conf:/etc/nginx/nginx.conf
        - /etc/nginx/cert/:/etc/nginx/cert/
        - /var/www/docsify/:/var/www/docsify/
    network_mode: host

  excalidraw:
    image: 'excalidraw/excalidraw:latest'
    container_name: excalidraw
    restart: unless-stopped
    ports:
      - '5000:80'

  alist:
      container_name: alist
      image: 'xhofe/alist:latest'
      restart: unless-stopped
      volumes:
          - '/etc/alist:/opt/alist/data'
      ports:
          - '5244:5244'

  v2ray:
      container_name: v2ray
      image: 'v2fly/v2fly-core'
      restart: unless-stopped
      volumes:
          - '/etc/v2ray:/etc/v2ray'
      ports:
          - '10086:10086'
      command: run -c /etc/v2ray/config.json 
