version: "3.0"
services:
  excalidraw:
    image: 'excalidraw/excalidraw:latest'
    container_name: excalidraw
    restart: unless-stopped
    ports:
      - '5000:80'

  v2ray:
      container_name: v2ray
      image: 'v2fly/v2fly-core'
      restart: unless-stopped
      volumes:
          - '/etc/v2ray:/etc/v2ray'
      ports:
          - '10086:10086'
      command: run -c /etc/v2ray/config.json 
