version: '2.1'

services:
  openwrt:
    container_name: openwrt
    restart: unless-stopped
    image: registry.cn-shanghai.aliyuncs.com/suling/openwrt:latest
    environment:
       - TZ=Asia/Shanghai
    privileged: true
    cap_add:
      - NET_ADMIN
    hostname: openwrt
    stop_signal: SIGKILL
    # volumes:
    #   - ./config:/etc/config
    #   - ./etc/shadow:/etc/shadow
    #   - ./etc/firewall.user:/etc/firewall.user
    #   - ./etc/passwall:/usr/share/passwall/rules
    command: ["/sbin/init"]
    networks:
      - openwrt_vlan

networks:
  openwrt_vlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: "192.168.1.0/24"
          gateway: "192.168.1.1"
