version: "3.0"
services:
  v2ray:
      container_name: v2ray
      restart: unless-stopped
      image: v2fly/v2fly-core
      volumes:
          - /etc/v2ray:/etc/v2ray
      ports:
          - 10086:10086
      command: run -c /etc/v2ray/config.json
