version: '3'
services:
  webdav:
    container_name: webdav
    image: bytemark/webdav
    restart: always
    ports:
      - "82:80"
    environment:
      AUTH_TYPE: Basic
      USERNAME: jyf
      PASSWORD: 7788
    volumes:
      - webdav-data:/var/lib/dav/data
      - /home/syncthing/org/agenda/:/var/lib/dav/data/agenda

volumes:
  webdav-data:
